server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Vue Router history mode 지원
    location / {
        try_files $uri $uri/ /index.html;
    }

    # vacation-api로 프록시
    location /api/ {
        proxy_pass http://vacation-api-svc/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
